<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

/**
 * List of available channels.
 */
class ChannelEnum
{
    /**
     * Dedicated for `WhatsApp` channel.
     */
    const WHATSAPP = "whatsapp";

    /**
     * Dedicated for `Messenger` channel.
     */
    const MESSENGER = "messenger";

    /**
     * Dedicated for `SMS` channel.
     */
    const SMS = "sms";

    /**
     * Twitter
     */
    const TWITTER = "twitter";
}
