<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Contacts Message Structure
 */
class ContactsMessageStructure implements JsonSerializable
{
    /**
     * contacts array
     * @required
     * @var \ConversationsAPILib\Models\SingleContactStructure[] $contacts public property
     */
    public $contacts;

    /**
     * type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $contacts Initialization value for $this->contacts
     * @param string $type     Initialization value for $this->type
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 2:
                $this->contacts = func_get_arg(0);
                $this->type     = func_get_arg(1);
                break;

            default:
                $this->type = MessageContentTypeEnum::CONTACT;
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['contacts'] = $this->contacts;
        $json['type']     = $this->type;

        return $json;
    }
}
