<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ContactRequestStructure implements JsonSerializable
{
    /**
     * List of contacts
     * @required
     * @var array $contacts public property
     */
    public $contacts;

    /**
     * Channel name
     * @required
     * @var string $channel public property
     */
    public $channel;

    /**
     * Constructor to set initial or default values of member properties
     * @param array  $contacts Initialization value for $this->contacts
     * @param string $channel  Initialization value for $this->channel
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->contacts = func_get_arg(0);
            $this->channel  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['contacts'] = $this->contacts;
        $json['channel']  = $this->channel;

        return $json;
    }
}
