<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CurrencyStructure implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $code public property
     */
    public $code;

    /**
     * @todo Write general description for this property
     * @required
     * @var double $value public property
     */
    public $value;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $text public property
     */
    public $text;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $code  Initialization value for $this->code
     * @param double $value Initialization value for $this->value
     * @param string $text  Initialization value for $this->text
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->code  = func_get_arg(0);
            $this->value = func_get_arg(1);
            $this->text  = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['code']  = $this->code;
        $json['value'] = $this->value;
        $json['text']  = $this->text;

        return $json;
    }
}
