<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *List Message Structure
 */
class ListMessageStructure implements JsonSerializable
{
    /**
     * type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * header
     * @required
     * @var \ConversationsAPILib\Models\MessageHeader $header public property
     */
    public $header;

    /**
     * body
     * @required
     * @var string $body public property
     */
    public $body;

    /**
     * footer
     * @required
     * @var \ConversationsAPILib\Models\MessageFooter $footer public property
     */
    public $footer;

    /**
     * button
     * @required
     * @var string $button public property
     */
    public $button;

    /**
     * sections
     * @required
     * @var \ConversationsAPILib\Models\SingleListMessageSection[] $sections public property
     */
    public $sections;

    /**
     * Constructor to set initial or default values of member properties
     * @param string        $type     Initialization value for $this->type
     * @param MessageHeader $header   Initialization value for $this->header
     * @param string        $body     Initialization value for $this->body
     * @param MessageFooter $footer   Initialization value for $this->footer
     * @param string        $button   Initialization value for $this->button
     * @param array         $sections Initialization value for $this->sections
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 6:
                $this->type     = func_get_arg(0);
                $this->header   = func_get_arg(1);
                $this->body     = func_get_arg(2);
                $this->footer   = func_get_arg(3);
                $this->button   = func_get_arg(4);
                $this->sections = func_get_arg(5);
                break;

            default:
                $this->type = MessageContentTypeEnum::LISTMESSAGE;
                $this->body = 'body';
                $this->button = 'button';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']     = $this->type;
        $json['header']   = $this->header;
        $json['body']     = $this->body;
        $json['footer']   = $this->footer;
        $json['button']   = $this->button;
        $json['sections'] = $this->sections;

        return $json;
    }
}
