<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Location Message Structure
 */
class LocationMessageStructure implements JsonSerializable
{
    /**
     * type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * location
     * @required
     * @var \ConversationsAPILib\Models\LocationStructure $location public property
     */
    public $location;

    /**
     * Constructor to set initial or default values of member properties
     * @param string            $type     Initialization value for $this->type
     * @param LocationStructure $location Initialization value for $this->location
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 2:
                $this->type     = func_get_arg(0);
                $this->location = func_get_arg(1);
                break;

            default:
                $this->type = MessageContentTypeEnum::LOCATION;
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']     = $this->type;
        $json['location'] = $this->location;

        return $json;
    }
}
