<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Fallback to sms channel. Fallback is not accepted for `template` type content
 */
class MessageFallbackStructure implements JsonSerializable
{
    /**
     * SMS fallback requires `sms` value.
     * @required
     * @var string $channel public property
     */
    public $channel;

    /**
     * E164 format with + at the beginning required
     * @required
     * @var string $contact public property
     */
    public $contact;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $channel Initialization value for $this->channel
     * @param string $contact Initialization value for $this->contact
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->channel = func_get_arg(0);
            $this->contact = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['channel'] = $this->channel;
        $json['contact'] = $this->contact;

        return $json;
    }
}
