<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Response sent when a message is successfully queued
 */
class MessageSuccessfullyQueuedResponse implements JsonSerializable
{
    /**
     * The message
     * @required
     * @var string $message public property
     */
    public $message;

    /**
     * The Identifier of the queued message
     * @required
     * @var string $messageId public property
     */
    public $messageId;

    /**
     * The Application ID through which the message was queued
     * @required
     * @var string $applicationId public property
     */
    public $applicationId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $message       Initialization value for $this->message
     * @param string $messageId     Initialization value for $this->messageId
     * @param string $applicationId Initialization value for $this->applicationId
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->message       = func_get_arg(0);
            $this->messageId     = func_get_arg(1);
            $this->applicationId = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['message']       = $this->message;
        $json['messageId']     = $this->messageId;
        $json['applicationId'] = $this->applicationId;

        return $json;
    }
}
