<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

/**
 * List of possible message content types.
 */
class MessageContentTypeEnum
{
    /**
     * Dedicated for message with `text` type content.
     */
    const TEXT = "text";

    /**
     * Dedicated for message with `template` type content.
     */
    const TEMPLATE = "template";

    /**
     * Dedicated for message with `image` type content.
     */
    const IMAGE = "image";

    /**
     * Dedicated for message with `audio` type content.
     */
    const AUDIO = "audio";

    /**
     * Dedicated for message with `video` type content.
     */
    const VIDEO = "video";

    /**
     * Dedicated for message with `file` type content.
     */
    const FILE = "file";

    /**
     * Dedicated for message with `ListMessage` type content. Messages including a menu of up to 10 options.
     * This type of message offers a simpler and more consistent way for users to make a selection when
     * interacting with a business.
     */
    const LISTMESSAGE = "listMessage";

    /**
     * Dedicated for message with `replyButton` type content. Messages including up to 3 options —each
     * option is a button. This type of message offers a quicker way for users to make a selection from a
     * menu when interacting with a business. Reply buttons have the same user experience as interactive
     * templates with buttons.
     */
    const REPLYBUTTON = "replyButton";

    /**
     * Dedicated for message with `location` type content. Messages including a location.
     */
    const LOCATION = "location";

    /**
     * Dedicated for message with `contact` type content. Messages including a contact.
     */
    const CONTACT = "contacts";

    /**
     * Dedicated for message with `product` type content. Messages including a single product from a
     * catalog.
     */
    const SINGLEPRODUCT = "product";

    /**
     * Dedicated for message with `productList` type content. Messages including multiple products from a
     * catalog.
     */
    const PRODUCTLIST = "productList";
}
