<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Message Header
 */
class MessageHeader implements JsonSerializable
{
    /**
     * type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * text
     * @required
     * @var string $text public property
     */
    public $text;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $type Initialization value for $this->type
     * @param string $text Initialization value for $this->text
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 2:
                $this->type = func_get_arg(0);
                $this->text = func_get_arg(1);
                break;

            default:
                $this->type = 'text';
                $this->text = 'header text';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type'] = $this->type;
        $json['text'] = $this->text;

        return $json;
    }
}
