<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Message Footer
 */
class MessageFooter implements JsonSerializable
{
    /**
     * text
     * @required
     * @var string $text public property
     */
    public $text;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $text Initialization value for $this->text
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 1:
                $this->text = func_get_arg(0);
                break;

            default:
                $this->text = 'footer text';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['text'] = $this->text;

        return $json;
    }
}
