<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Product List Message Structure
 */
class ProductListMessageStructure implements JsonSerializable
{
    /**
     * type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * header
     * @required
     * @var \ConversationsAPILib\Models\MessageHeader $header public property
     */
    public $header;

    /**
     * body
     * @required
     * @var string $body public property
     */
    public $body;

    /**
     * footer
     * @var \ConversationsAPILib\Models\MessageFooter|null $footer public property
     */
    public $footer;

    /**
     * category
     * @var string|null $category public property
     */
    public $category;

    /**
     * catalogId
     * @var string|null $catalogId public property
     */
    public $catalogId;

    /**
     * sections
     * @var \ConversationsAPILib\Models\SingleProductSection[]|null $sections public property
     */
    public $sections;

    /**
     * Constructor to set initial or default values of member properties
     * @param string        $type      Initialization value for $this->type
     * @param MessageHeader $header    Initialization value for $this->header
     * @param string        $body      Initialization value for $this->body
     * @param MessageFooter $footer    Initialization value for $this->footer
     * @param string        $category  Initialization value for $this->category
     * @param string        $catalogId Initialization value for $this->catalogId
     * @param array         $sections  Initialization value for $this->sections
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 7:
                $this->type      = func_get_arg(0);
                $this->header    = func_get_arg(1);
                $this->body      = func_get_arg(2);
                $this->footer    = func_get_arg(3);
                $this->category  = func_get_arg(4);
                $this->catalogId = func_get_arg(5);
                $this->sections  = func_get_arg(6);
                break;

            default:
                $this->type = MessageContentTypeEnum::PRODUCTLIST;
                $this->body = 'body';
                $this->category = 'category';
                $this->catalogId = '234242534234234234';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']      = $this->type;
        $json['header']    = $this->header;
        $json['body']      = $this->body;
        $json['footer']    = $this->footer;
        $json['category']  = $this->category;
        $json['catalogId'] = $this->catalogId;
        $json['sections']  = $this->sections;

        return $json;
    }
}
