<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *This message type is only supported in Messenger.
 */
class QuickRepliesMessageStructure implements JsonSerializable
{
    /**
     * This type of content requires `text` value.
     * @var string $type public property
     */
    public $type = 'text';

    /**
     * Message text to send with the quick replies
     * @required
     * @var string $text public property
     */
    public $text;

    /**
     * Representation of quick replies
     * @required
     * @var array $options public property
     */
    public $options;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $type    Initialization value for $this->type
     * @param string $text    Initialization value for $this->text
     * @param array  $options Initialization value for $this->options
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 3:
                $this->type    = func_get_arg(0);
                $this->text    = func_get_arg(1);
                $this->options = func_get_arg(2);
                break;

            default:
                $this->type = 'text';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']    = $this->type;
        $json['text']    = $this->text;
        $json['options'] = $this->options;

        return $json;
    }
}
