<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *ReplyButton Message Structure
 */
class ReplyButtonMessageStructure implements JsonSerializable
{
    /**
     * type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * header
     * @required
     * @var \ConversationsAPILib\Models\MessageHeader $header public property
     */
    public $header;

    /**
     * body
     * @required
     * @var string $body public property
     */
    public $body;

    /**
     * footer
     * @required
     * @var \ConversationsAPILib\Models\MessageFooter $footer public property
     */
    public $footer;

    /**
     * buttons
     * @required
     * @var \ConversationsAPILib\Models\SingleReplyButtonMessageButton[] $buttons public property
     */
    public $buttons;

    /**
     * Constructor to set initial or default values of member properties
     * @param string        $type    Initialization value for $this->type
     * @param MessageHeader $header  Initialization value for $this->header
     * @param string        $body    Initialization value for $this->body
     * @param MessageFooter $footer  Initialization value for $this->footer
     * @param array         $buttons Initialization value for $this->buttons
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 5:
                $this->type    = func_get_arg(0);
                $this->header  = func_get_arg(1);
                $this->body    = func_get_arg(2);
                $this->footer  = func_get_arg(3);
                $this->buttons = func_get_arg(4);
                break;

            default:
                $this->type = MessageContentTypeEnum::REPLYBUTTON;
                $this->body = 'body';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']    = $this->type;
        $json['header']  = $this->header;
        $json['body']    = $this->body;
        $json['footer']  = $this->footer;
        $json['buttons'] = $this->buttons;

        return $json;
    }
}
