<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Single Contact Structure
 */
class SingleContactStructure implements JsonSerializable
{
    /**
     * name
     * @required
     * @var \ConversationsAPILib\Models\SingleContactStructureName $name public property
     */
    public $name;

    /**
     * addresses
     * @required
     * @var \ConversationsAPILib\Models\SingleContactStructureAddress[] $addresses public property
     */
    public $addresses;

    /**
     * birthday
     * @required
     * @var string $birthday public property
     */
    public $birthday;

    /**
     * emails
     * @required
     * @var \ConversationsAPILib\Models\SingleContactStructureEmail[] $emails public property
     */
    public $emails;

    /**
     * org
     * @required
     * @var \ConversationsAPILib\Models\SingleContactStructureOrganization $org public property
     */
    public $org;

    /**
     * phones
     * @required
     * @var \ConversationsAPILib\Models\SingleContactStructurePhone[] $phones public property
     */
    public $phones;

    /**
     * urls
     * @required
     * @var \ConversationsAPILib\Models\SingleContactStructureURL[] $urls public property
     */
    public $urls;

    /**
     * Constructor to set initial or default values of member properties
     * @param SingleContactStructureName         $name      Initialization value for $this->name
     * @param array                              $addresses Initialization value for $this->addresses
     * @param string                             $birthday  Initialization value for $this->birthday
     * @param array                              $emails    Initialization value for $this->emails
     * @param SingleContactStructureOrganization $org       Initialization value for $this->org
     * @param array                              $phones    Initialization value for $this->phones
     * @param array                              $urls      Initialization value for $this->urls
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 7:
                $this->name      = func_get_arg(0);
                $this->addresses = func_get_arg(1);
                $this->birthday  = func_get_arg(2);
                $this->emails    = func_get_arg(3);
                $this->org       = func_get_arg(4);
                $this->phones    = func_get_arg(5);
                $this->urls      = func_get_arg(6);
                break;

            default:
                $this->birthday = '2002-11-11';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']      = $this->name;
        $json['addresses'] = $this->addresses;
        $json['birthday']  = $this->birthday;
        $json['emails']    = $this->emails;
        $json['org']       = $this->org;
        $json['phones']    = $this->phones;
        $json['urls']      = $this->urls;

        return $json;
    }
}
