<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Single ListMessage Row
 */
class SingleListMessageRow implements JsonSerializable
{
    /**
     * id
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * title
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * description
     * @var string|null $description public property
     */
    public $description;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $id          Initialization value for $this->id
     * @param string $title       Initialization value for $this->title
     * @param string $description Initialization value for $this->description
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 3:
                $this->id          = func_get_arg(0);
                $this->title       = func_get_arg(1);
                $this->description = func_get_arg(2);
                break;

            default:
                $this->id = 'id';
                $this->title = 'title';
                $this->description = 'description';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']          = $this->id;
        $json['title']       = $this->title;
        $json['description'] = $this->description;

        return $json;
    }
}
