<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Single Contact Structure Email
 */
class SingleContactStructureEmail implements JsonSerializable
{
    /**
     * email
     * @required
     * @var string $email public property
     */
    public $email;

    /**
     * type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $email Initialization value for $this->email
     * @param string $type  Initialization value for $this->type
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 2:
                $this->email = func_get_arg(0);
                $this->type  = func_get_arg(1);
                break;

            default:
                $this->email = 'email@example.com';
                $this->type = 'WORK';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['email'] = $this->email;
        $json['type']  = $this->type;

        return $json;
    }
}
