<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Single ListMessage Section
 */
class SingleListMessageSection implements JsonSerializable
{
    /**
     * title
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * rows
     * @required
     * @var \ConversationsAPILib\Models\SingleListMessageRow[] $rows public property
     */
    public $rows;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $title Initialization value for $this->title
     * @param array  $rows  Initialization value for $this->rows
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 2:
                $this->title = func_get_arg(0);
                $this->rows  = func_get_arg(1);
                break;

            default:
                $this->title = 'title';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['title'] = $this->title;
        $json['rows']  = $this->rows;

        return $json;
    }
}
