<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Single Product Item
 */
class SingleProductItem implements JsonSerializable
{
    /**
     * productRetailerId
     * @required
     * @var string $productRetailerId public property
     */
    public $productRetailerId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $productRetailerId Initialization value for $this->productRetailerId
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 1:
                $this->productRetailerId = func_get_arg(0);
                break;

            default:
                $this->productRetailerId = 'productRetailerId';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['productRetailerId'] = $this->productRetailerId;

        return $json;
    }
}
