<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Single Contact Structure organization
 */
class SingleContactStructureOrganization implements JsonSerializable
{
    /**
     * name
     * @required
     * @var string $company public property
     */
    public $company;

    /**
     * department
     * @required
     * @var string $department public property
     */
    public $department;

    /**
     * title
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $company    Initialization value for $this->company
     * @param string $department Initialization value for $this->department
     * @param string $title      Initialization value for $this->title
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 3:
                $this->company    = func_get_arg(0);
                $this->department = func_get_arg(1);
                $this->title      = func_get_arg(2);
                break;

            default:
                $this->company = 'Unifonic';
                $this->department = 'Engineering';
                $this->title = 'Eng.';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['company']    = $this->company;
        $json['department'] = $this->department;
        $json['title']      = $this->title;

        return $json;
    }
}
