<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Single Product Section
 */
class SingleProductSection implements JsonSerializable
{
    /**
     * title
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * productItems
     * @required
     * @var \ConversationsAPILib\Models\SingleProductItem[] $productItems public property
     */
    public $productItems;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $title        Initialization value for $this->title
     * @param array  $productItems Initialization value for $this->productItems
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 2:
                $this->title        = func_get_arg(0);
                $this->productItems = func_get_arg(1);
                break;

            default:
                $this->title = 'title';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['title']        = $this->title;
        $json['productItems'] = $this->productItems;

        return $json;
    }
}
