<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Template Component Media Parameter
 */
class TemplateComponentMediaParameter extends TemplateComponentParameter implements JsonSerializable
{
    /**
     * Media URL
     * @required
     * @var string $url public property
     */
    public $url;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $url Initialization value for $this->url
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->url = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['url'] = $this->url;
        $json = array_merge($json, parent::jsonSerialize());

        return $json;
    }
}
