<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Template Component Parameter Base Type
 */
class TemplateComponentParameter implements JsonSerializable
{
    /**
     * Parameter Type
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Parameters
     * @required
     * @var array $parameters public property
     */
    public $parameters;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $type       Initialization value for $this->type
     * @param array  $parameters Initialization value for $this->parameters
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->type       = func_get_arg(0);
            $this->parameters = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']       = $this->type;
        $json['parameters'] = $this->parameters;

        return $json;
    }
}
