<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Template Component Date Time Parameter type
 */
class TemplateComponentDateTimeParameter extends TemplateComponentParameter implements JsonSerializable
{
    /**
     * Date Time Structure
     * @required
     * @var \ConversationsAPILib\Models\TemplateComponentDateTimeParameterBody $datetime public property
     */
    public $datetime;

    /**
     * Constructor to set initial or default values of member properties
     * @param TemplateComponentDateTimeParameterBody $datetime Initialization value for $this->datetime
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->datetime = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['datetime'] = $this->datetime;
        $json = array_merge($json, parent::jsonSerialize());

        return $json;
    }
}
