<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Code for language
 */
class TemplateLanguageCodeStructure implements JsonSerializable
{
    /**
     * Language Code
     * @required
     * @var string $code public property
     */
    public $code;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $code Initialization value for $this->code
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 1:
                $this->code = func_get_arg(0);
                break;

            default:
                $this->code = 'en';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['code'] = $this->code;

        return $json;
    }
}
