<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Template Component Option Parameter
 */
class TemplateComponentOptionParameter extends TemplateComponentParameter implements JsonSerializable
{
    /**
     * Value
     * @required
     * @var string $value public property
     */
    public $value;

    /**
     * Option Sub Type
     * @required
     * @var string $subType public property
     */
    public $subType;

    /**
     * Zero based index of the position of the option as it appears on WhatsApp Business Manager template
     * configuration page
     * @required
     * @var integer $index public property
     */
    public $index;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $value   Initialization value for $this->value
     * @param string  $subType Initialization value for $this->subType
     * @param integer $index   Initialization value for $this->index
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->value   = func_get_arg(0);
            $this->subType = func_get_arg(1);
            $this->index   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['value']   = $this->value;
        $json['subType'] = $this->subType;
        $json['index']   = $this->index;
        $json = array_merge($json, parent::jsonSerialize());

        return $json;
    }
}
