<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Template Component Parameter Date Time Structure Body
 */
class TemplateComponentDateTimeParameterBody implements JsonSerializable
{
    /**
     * Value
     * @required
     * @var string $value public property
     */
    public $value;

    /**
     * Text
     * @required
     * @var string $text public property
     */
    public $text;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $value Initialization value for $this->value
     * @param string $text  Initialization value for $this->text
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->value = func_get_arg(0);
            $this->text  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['value'] = $this->value;
        $json['text']  = $this->text;

        return $json;
    }
}
