<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

/**
 * Template Component Parameter Option Sub Types
 */
class TemplateComponentParameterOptionSubTypesEnum
{
    /**
     * URL
     */
    const URL = "url";

    /**
     * Quick Reply Button
     */
    const QUICKREPLY = "quickReply";
}
