<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

/**
 * Template Component Parameter Types
 */
class TemplateComponentParameterTypesEnum
{
    /**
     * Image Parameter type
     */
    const IMAGE = "image";

    /**
     * Document Parameter type
     */
    const DOCUMENT = "document";

    /**
     * File Parameter type
     */
    const FILE = "file";

    /**
     * Text Parameter Type
     */
    const TEXT = "text";

    /**
     * Date Time Parameter Type
     */
    const DATETIME = "datetime";

    /**
     * Currency Parameter Type
     */
    const CURRENCY = "currency";
}
