<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class TemplateComponentTypesEnum
{
    /**
     * Template Header Component
     */
    const HEADER = "header";

    /**
     * Template Component Body
     */
    const BODY = "body";

    /**
     * Action Button Options
     */
    const OPTIONS = "options";
}
