<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Parameters set up for the specified template as defined in Facebook Business Manager. This is
 * related to Template Message.
 */
class TemplateMessageParameters implements JsonSerializable
{
    /**
     * The value of the parameter.
     * @required
     * @maps default
     * @var string $mdefault public property
     */
    public $mdefault;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $mdefault Initialization value for $this->mdefault
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->mdefault = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['default'] = $this->mdefault;

        return $json;
    }
}
