<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib\Models;

use JsonSerializable;

/**
 *Template Component Text Parameter type
 */
class TemplateComponentTextParameter extends TemplateComponentParameter implements JsonSerializable
{
    /**
     * Text value
     * @required
     * @var string $text public property
     */
    public $text;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $text Initialization value for $this->text
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->text = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['text'] = $this->text;
        $json = array_merge($json, parent::jsonSerialize());

        return $json;
    }
}
