<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The environment being used'
     * @var string
     */
    public static $environment = Environments::SANDBOX;

    /**
     * PublicId from application's API keys tab.
     * @var string
     */
    public static $publicId = '{{PublicId}}';

    /**
     * Secret from application's API keys tab.
     * @var string
     */
    public static $secret = '{{Secret}}';

    /**
     * Get the base uri for a given server in the current environment
     * @param  string $server Server name
     * @return string         Base URI
     */
    public static function getBaseUri($server = Servers::BASE_URL)
    {
        return APIHelper::appendUrlWithTemplateParameters(
            static::$environmentsMap[static::$environment][$server],
            array(
            )
        );
    }

    /**
     * A map of all baseurls used in different environments and servers
     * @var array
     */
    private static $environmentsMap = array(
        Environments::PRODUCTION => array(
            Servers::BASE_URL => 'https://apis.unifonic.com',
        ),
        Environments::SANDBOX => array(
            Servers::BASE_URL => 'https://apis.unifonic.com',
        ),
    );
}
