<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib;

use ConversationsAPILib\Controllers;

/**
 * ConversationsAPILib client class
 */
class ConversationsAPIClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $publicId = null,
        $secret = null
    ) {
        Configuration::$publicId = $publicId ? $publicId : Configuration::$publicId;
        Configuration::$secret = $secret ? $secret : Configuration::$secret;
    }
    /**
     * Singleton access to OutboundMessages controller
     * @return Controllers\OutboundMessagesController The *Singleton* instance
     */
    public function getOutboundMessages()
    {
        return Controllers\OutboundMessagesController::getInstance();
    }
    /**
     * Singleton access to WhatsappOutboundTemplateMessage controller
     * @return Controllers\WhatsappOutboundTemplateMessageController The *Singleton* instance
     */
    public function getWhatsappOutboundTemplateMessage()
    {
        return Controllers\WhatsappOutboundTemplateMessageController::getInstance();
    }
    /**
     * Singleton access to WhatsappOutboundSessionMessage controller
     * @return Controllers\WhatsappOutboundSessionMessageController The *Singleton* instance
     */
    public function getWhatsappOutboundSessionMessage()
    {
        return Controllers\WhatsappOutboundSessionMessageController::getInstance();
    }
}
