<?php
/*
 * ConversationsAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ConversationsAPILib;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * This URL lets you connect to the production Unifonic API.
     */
    const PRODUCTION = "Production";

    /**
     * This URL lets you connect to our sandbox environment in production
     */
    const SANDBOX = "Sandbox";
}
